### ISSUE TITLE
Active check in "Elasticsearch: Index discovery"

### ISSUE THREAD

**Issue by nblock** [sergiotocalini/elasix#1]
I'm using your project, thank a lot for releasing it!

The item prototypes for "Elasticsearch: Index discovery" are using `Zabbix Agent (active)` as type. All other items are using the passive variant. Maybe this is a misconfiguration, maybe active checks are intended. Active checks are not mentioned in the README, so I modified the template to use passive checks everywhere.

This avoids items without data and the trigger "More than 100 items having missing data for more than 10 minutes"

**Comment by sergiotocalini** [comment]
Indeed, it was a mistake and I forgot to upload the new template. Now, it should be updated.
You are welcome, enjoy it ;)
