### ISSUE TITLE
Spaces on the template and other issues.

### ISSUE THREAD

**Issue by aguzmans** [sergiotocalini/elasix#2]
HI,

I recently installed one instance running ES using your monitoring template. The template seems GREAT so far. I have to do a lot of tweaking around, etc. SO I am going to talk about that here.
In the template there are spaces between the different items and it does not seem to work. DO no know if on that I should do something about them.

```
~# zabbix_agentd -t elasix[stat,health,unassigned_shards] -c /etc/zabbix/zabbix_agentd.conf
elasix[stat,health,unassigned_shards]         [t|10]

~# zabbix_agentd -t elasix[stat, health, unassigned_shards] -c /etc/zabbix/zabbix_agentd.conf
zabbix_agentd [2420]: invalid parameter "health,"
zabbix_agentd [2420]: invalid parameter "unassigned_shards]"
~#
```

What would I need to do to get this working. 
This is a standard ubuntu 16.04.
This might be because I used zabbix 4.2, but I used zabbix 4.2 and it does not imports correctly.

**Comment by sergiotocalini** [comment]
Hi @aguzmans 
It is happening because bash is escaping the strings and you should pass all the key as a unique string. Please try the following:
```
~# zabbix_agentd -t "elasix[stat, health, unassigned_shards]" -c /etc/zabbix/zabbix_agentd.conf
```
